# Generated by Django 4.2.6 on 2023-10-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
