# Generated by Django 4.2.6 on 2023-10-25 13:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_time_stamp_order_order_date_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Upload_to_UserMedicine),
        ),
    ]
