# Generated by Django 4.2.6 on 2023-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('placed', 'placed'), ('processed', 'processed'), ('delivered', 'delivered'), ('canceld', 'canceld')], max_length=10),
        ),
    ]
